name: Latest blog post workflow

on:
  schedule:
    # Run at minute 0 of every hour (UTC)
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://blog.olimorris.com/feed.xml
          readme-section: feed
